package model.pojos;
// Generated 15 ene 2025, 17:43:24 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Modules generated by hbm2java
 */
public class Modules implements java.io.Serializable {

	private Long id;
	private Cycles cycles;
	private Users users;
	private String code;
	private String name;
	private int hours;
	private byte course;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Set enrollmentses = new HashSet(0);
	private Set scheduleses = new HashSet(0);

	public Modules() {
	}

	public Modules(Cycles cycles, String code, String name, int hours, byte course) {
		this.cycles = cycles;
		this.code = code;
		this.name = name;
		this.hours = hours;
		this.course = course;
	}

	public Modules(Cycles cycles, Users users, String code, String name, int hours, byte course, Timestamp createdAt,
			Timestamp updatedAt, Set enrollmentses, Set scheduleses) {
		this.cycles = cycles;
		this.users = users;
		this.code = code;
		this.name = name;
		this.hours = hours;
		this.course = course;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.enrollmentses = enrollmentses;
		this.scheduleses = scheduleses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Cycles getCycles() {
		return this.cycles;
	}

	public void setCycles(Cycles cycles) {
		this.cycles = cycles;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getHours() {
		return this.hours;
	}

	public void setHours(int hours) {
		this.hours = hours;
	}

	public byte getCourse() {
		return this.course;
	}

	public void setCourse(byte course) {
		this.course = course;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getEnrollmentses() {
		return this.enrollmentses;
	}

	public void setEnrollmentses(Set enrollmentses) {
		this.enrollmentses = enrollmentses;
	}

	public Set getScheduleses() {
		return this.scheduleses;
	}

	public void setScheduleses(Set scheduleses) {
		this.scheduleses = scheduleses;
	}

}
