package model.pojos;
// Generated 15 ene 2025, 17:39:33 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Participants generated by hbm2java
 */
public class Participants implements java.io.Serializable {

	private Long id;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private long meetingId;
	private long userId;
	private String status;

	public Participants() {
	}

	public Participants(long meetingId, long userId, String status) {
		this.meetingId = meetingId;
		this.userId = userId;
		this.status = status;
	}

	public Participants(Timestamp createdAt, Timestamp updatedAt, long meetingId, long userId, String status) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.meetingId = meetingId;
		this.userId = userId;
		this.status = status;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public long getMeetingId() {
		return this.meetingId;
	}

	public void setMeetingId(long meetingId) {
		this.meetingId = meetingId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
