package model.pojos;
// Generated 15 ene 2025, 17:39:33 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Long id;
	private Roles roles;
	private String name;
	private String email;
	private Timestamp emailVerifiedAt;
	private String password;
	private String rememberToken;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Timestamp deletedAt;
	private String lastname;
	private String pin;
	private String address;
	private String phone1;
	private String phone2;
	private byte[] photo;
	private boolean intensive;
	private Set moduleses = new HashSet(0);
	private Set enrollmentses = new HashSet(0);
	private Set meetingses = new HashSet(0);

	public Users() {
	}

	public Users(String name, String email, String password, String lastname, String pin, String address, String phone1,
			boolean intensive) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.lastname = lastname;
		this.pin = pin;
		this.address = address;
		this.phone1 = phone1;
		this.intensive = intensive;
	}

	public Users(Roles roles, String name, String email, Timestamp emailVerifiedAt, String password,
			String rememberToken, Timestamp createdAt, Timestamp updatedAt, Timestamp deletedAt, String lastname,
			String pin, String address, String phone1, String phone2, byte[] photo, boolean intensive, Set moduleses,
			Set enrollmentses, Set meetingses) {
		this.roles = roles;
		this.name = name;
		this.email = email;
		this.emailVerifiedAt = emailVerifiedAt;
		this.password = password;
		this.rememberToken = rememberToken;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.lastname = lastname;
		this.pin = pin;
		this.address = address;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.photo = photo;
		this.intensive = intensive;
		this.moduleses = moduleses;
		this.enrollmentses = enrollmentses;
		this.meetingses = meetingses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Timestamp getEmailVerifiedAt() {
		return this.emailVerifiedAt;
	}

	public void setEmailVerifiedAt(Timestamp emailVerifiedAt) {
		this.emailVerifiedAt = emailVerifiedAt;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRememberToken() {
		return this.rememberToken;
	}

	public void setRememberToken(String rememberToken) {
		this.rememberToken = rememberToken;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Timestamp getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Timestamp deletedAt) {
		this.deletedAt = deletedAt;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	public boolean isIntensive() {
		return this.intensive;
	}

	public void setIntensive(boolean intensive) {
		this.intensive = intensive;
	}

	public Set getModuleses() {
		return this.moduleses;
	}

	public void setModuleses(Set moduleses) {
		this.moduleses = moduleses;
	}

	public Set getEnrollmentses() {
		return this.enrollmentses;
	}

	public void setEnrollmentses(Set enrollmentses) {
		this.enrollmentses = enrollmentses;
	}

	public Set getMeetingses() {
		return this.meetingses;
	}

	public void setMeetingses(Set meetingses) {
		this.meetingses = meetingses;
	}

}
