package elorbase.model.pojos;
// Generated 15 ene 2025, 19:12:17 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Cycles generated by hbm2java
 */
public class Cycles implements java.io.Serializable {

	private Long id;
	private String code;
	private String name;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Set moduleses = new HashSet(0);

	public Cycles() {
	}

	public Cycles(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public Cycles(String code, String name, Timestamp createdAt, Timestamp updatedAt, Set moduleses) {
		this.code = code;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.moduleses = moduleses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getModuleses() {
		return this.moduleses;
	}

	public void setModuleses(Set moduleses) {
		this.moduleses = moduleses;
	}

}
