package elorbase.model.pojos;
// Generated 15 ene 2025, 17:43:24 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private Long id;
	private String role;
	private String description;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Set userses = new HashSet(0);

	public Roles() {
	}

	public Roles(String role, String description) {
		this.role = role;
		this.description = description;
	}

	public Roles(String role, String description, Timestamp createdAt, Timestamp updatedAt, Set userses) {
		this.role = role;
		this.description = description;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.userses = userses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
