package server.elorbase.model;
// Generated 16 ene 2025, 15:45:15 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Participants generated by hbm2java
 */
public class Participants implements java.io.Serializable {

	private long id;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private long meetingId;
	private long userId;
	private String status;

	public Participants() {
	}

	public Participants(long id, long meetingId, long userId, String status) {
		this.id = id;
		this.meetingId = meetingId;
		this.userId = userId;
		this.status = status;
	}

	public Participants(long id, Timestamp createdAt, Timestamp updatedAt, long meetingId, long userId, String status) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.meetingId = meetingId;
		this.userId = userId;
		this.status = status;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public long getMeetingId() {
		return this.meetingId;
	}

	public void setMeetingId(long meetingId) {
		this.meetingId = meetingId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
