package server.elorbase.model;
// Generated 16 ene 2025, 15:45:15 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Schedules generated by hbm2java
 */
public class Schedules implements java.io.Serializable {

	private Long id;
	private Modules modules;
	private byte day;
	private byte hour;
	private Timestamp createdAt;
	private Timestamp updatedAt;

	public Schedules() {
	}

	public Schedules(Modules modules, byte day, byte hour) {
		this.modules = modules;
		this.day = day;
		this.hour = hour;
	}

	public Schedules(Modules modules, byte day, byte hour, Timestamp createdAt, Timestamp updatedAt) {
		this.modules = modules;
		this.day = day;
		this.hour = hour;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Modules getModules() {
		return this.modules;
	}

	public void setModules(Modules modules) {
		this.modules = modules;
	}

	public byte getDay() {
		return this.day;
	}

	public void setDay(byte day) {
		this.day = day;
	}

	public byte getHour() {
		return this.hour;
	}

	public void setHour(byte hour) {
		this.hour = hour;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

}
