package server.elorbase.entities;
// Generated 27 ene 2025, 20:21:03 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Transient;

/**
 * Documents generated by hbm2java
 */
@Entity
public class Document implements java.io.Serializable {

	private static final long serialVersionUID = 8203150317431826837L;
	@Id
	private Long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "module_id")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private Module module;
	
	private String name;
	private String extension;
	private String route;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	
	@Transient // Este campo no será persistido en la base de datos
    private byte[] file;

	public Document() {
	}

	public Document(Module module, String name, String extension, String route) {
		this.module = module;
		this.name = name;
		this.extension = extension;
		this.route = route;
	}

	public Document(Module module, String name, String extension, String route, Timestamp createdAt,
			Timestamp updatedAt) {
		this.module = module;
		this.name = name;
		this.extension = extension;
		this.route = route;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public byte[] getFile() {
		return file;
	}

	public void setFile(byte[] file) {
		this.file = file;
	}

}
