package server.elorbase.entities;
// Generated 27 ene 2025, 19:50:40 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Meetings generated by hbm2java
 */
public class Meeting implements java.io.Serializable {

	private Long id;
	private User user;
	private byte day;
	private byte time;
	private byte week;
	private String status;
	private String title;
	private Byte room;
	private String subject;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Set participants = new HashSet(0);

	public Meeting() {
	}

	public Meeting(User user, byte day, byte time, byte week, String status) {
		this.user = user;
		this.day = day;
		this.time = time;
		this.week = week;
		this.status = status;
	}

	public Meeting(User user, byte day, byte time, byte week, String status, String title, Byte room, String subject,
			Timestamp createdAt, Timestamp updatedAt, Set participants) {
		this.user = user;
		this.day = day;
		this.time = time;
		this.week = week;
		this.status = status;
		this.title = title;
		this.room = room;
		this.subject = subject;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.participants = participants;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUsers() {
		return this.user;
	}

	public void setUsers(User user) {
		this.user = user;
	}

	public byte getDay() {
		return this.day;
	}

	public void setDay(byte day) {
		this.day = day;
	}

	public byte getTime() {
		return this.time;
	}

	public void setTime(byte time) {
		this.time = time;
	}

	public byte getWeek() {
		return this.week;
	}

	public void setWeek(byte week) {
		this.week = week;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Byte getRoom() {
		return this.room;
	}

	public void setRoom(Byte room) {
		this.room = room;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getParticipants() {
		return this.participants;
	}

	public void setParticipants(Set participants) {
		this.participants = participants;
	}

}
