package server.elorbase.entities;
// Generated 18 ene 2025, 9:48:26 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Meetings generated by hbm2java
 */
public class Meeting implements java.io.Serializable {

	private Long id;
	private User user;
	private byte day;
	private byte time;
	private byte week;
	private String status;
	private Timestamp createdAt;
	private Timestamp updatedAt;

	public Meeting() {
	}

	public Meeting(User user, byte day, byte time, byte week, String status) {
		this.user = user;
		this.day = day;
		this.time = time;
		this.week = week;
		this.status = status;
	}

	public Meeting(User user, byte day, byte time, byte week, String status, Timestamp createdAt,
			Timestamp updatedAt) {
		this.user = user;
		this.day = day;
		this.time = time;
		this.week = week;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public byte getDay() {
		return this.day;
	}

	public void setDay(byte day) {
		this.day = day;
	}

	public byte getTime() {
		return this.time;
	}

	public void setTime(byte time) {
		this.time = time;
	}

	public byte getWeek() {
		return this.week;
	}

	public void setWeek(byte week) {
		this.week = week;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

}
