package server.elorbase.entities;
// Generated 18 ene 2025, 9:48:26 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;

/**
 * Modules generated by hbm2java
 */
@Entity
public class Module implements java.io.Serializable {

	private static final long serialVersionUID = -2981656318664124550L;
	
	@Id
	private Long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cycle_id")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private Cycle cycle;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private User user;
	
	private String code;
	private String name;
	private int hours;
	private byte course;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	
	@OneToMany(mappedBy = "module", fetch = FetchType.LAZY)
	@JsonBackReference
	private Set<Enrollment> enrollments = new HashSet<Enrollment>(0);
	
	@OneToMany(mappedBy = "module", fetch = FetchType.LAZY)
	@JsonBackReference
	private Set<Schedule> schedules = new HashSet<Schedule>(0);
	
	@OneToMany(mappedBy = "module", fetch = FetchType.LAZY)
	@JsonBackReference
	private Set<Document> documents = new HashSet<Document>(0);

	public Module() {
	}

	public Module(Cycle cycle, String code, String name, int hours, byte course) {
		this.cycle = cycle;
		this.code = code;
		this.name = name;
		this.hours = hours;
		this.course = course;
	}

	public Module(Cycle cycle, User user, String code, String name, int hours, byte course, Timestamp createdAt,
			Timestamp updatedAt, Set<Enrollment> enrollments, Set<Schedule> schedules, Set<Document> documents) {
		this.cycle = cycle;
		this.user = user;
		this.code = code;
		this.name = name;
		this.hours = hours;
		this.course = course;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.enrollments = enrollments;
		this.schedules = schedules;
		this.documents = documents;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Cycle getCycle() {
		return this.cycle;
	}

	public void setCycle(Cycle cycle) {
		this.cycle = cycle;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getHours() {
		return this.hours;
	}

	public void setHours(int hours) {
		this.hours = hours;
	}

	public byte getCourse() {
		return this.course;
	}

	public void setCourse(byte course) {
		this.course = course;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Enrollment> getEnrollments() {
		return this.enrollments;
	}

	public void setEnrollments(Set<Enrollment> enrollments) {
		this.enrollments = enrollments;
	}

	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

	public Set<Document> getDocuments() {
		return documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

}
