package server.elorbase.entities;
// Generated 18 ene 2025, 9:48:26 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Modules generated by hbm2java
 */
public class Module implements java.io.Serializable {

	private Long id;
	private Cycle cycle;
	private User user;
	private String code;
	private String name;
	private int hours;
	private byte course;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Set enrollments = new HashSet(0);
	private Set schedules = new HashSet(0);

	public Module() {
	}

	public Module(Cycle cycle, String code, String name, int hours, byte course) {
		this.cycle = cycle;
		this.code = code;
		this.name = name;
		this.hours = hours;
		this.course = course;
	}

	public Module(Cycle cycle, User user, String code, String name, int hours, byte course, Timestamp createdAt,
			Timestamp updatedAt, Set enrollments, Set schedules) {
		this.cycle = cycle;
		this.user = user;
		this.code = code;
		this.name = name;
		this.hours = hours;
		this.course = course;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.enrollments = enrollments;
		this.schedules = schedules;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Cycle getCycle() {
		return this.cycle;
	}

	public void setCycle(Cycle cycle) {
		this.cycle = cycle;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getHours() {
		return this.hours;
	}

	public void setHours(int hours) {
		this.hours = hours;
	}

	public byte getCourse() {
		return this.course;
	}

	public void setCourse(byte course) {
		this.course = course;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getEnrollments() {
		return this.enrollments;
	}

	public void setEnrollments(Set enrollments) {
		this.enrollments = enrollments;
	}

	public Set getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set schedules) {
		this.schedules = schedules;
	}

}
