package server.elorbase.entities;
// Generated 27 ene 2025, 19:50:40 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

/**
 * Participants generated by hbm2java
 */
@Entity
public class Participant implements java.io.Serializable {

	private static final long serialVersionUID = -7801031623015730999L;
	
	@Id
	private Long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private User user;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "meeting_id")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private Meeting meeting;
	
	private String status;
	private Timestamp createdAt;
	private Timestamp updatedAt;

	public Participant() {
	}

	public Participant(User user, Meeting meeting, String status) {
		this.user = user;
		this.meeting = meeting;
		this.status = status;
	}

	public Participant(User user, Meeting meeting, String status, Timestamp createdAt, Timestamp updatedAt) {
		this.user = user;
		this.meeting = meeting;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Meeting getMeeting() {
		return this.meeting;
	}

	public void setMeeting(Meeting meeting) {
		this.meeting = meeting;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

}
