package server.elorbase.entities;
// Generated 27 ene 2025, 19:50:40 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Participants generated by hbm2java
 */
public class Participant implements java.io.Serializable {

	private Long id;
	private User user;
	private Meeting meeting;
	private String status;
	private Timestamp createdAt;
	private Timestamp updatedAt;

	public Participant() {
	}

	public Participant(User user, Meeting meeting, String status) {
		this.user = user;
		this.meeting = meeting;
		this.status = status;
	}

	public Participant(User user, Meeting meetings, String status, Timestamp createdAt, Timestamp updatedAt) {
		this.user = user;
		this.meeting = meeting;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUsers(User user) {
		this.user = user;
	}

	public Meeting getMeeting() {
		return this.meeting;
	}

	public void setMeeting(Meeting meeting) {
		this.meeting = meeting;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

}
