package server.elorbase.entities;
// Generated 18 ene 2025, 9:48:26 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Schedules generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	private Long id;
	private Module module;
	private byte day;
	private byte hour;
	private Timestamp createdAt;
	private Timestamp updatedAt;

	public Schedule() {
	}

	public Schedule(Module module, byte day, byte hour) {
		this.module = module;
		this.day = day;
		this.hour = hour;
	}

	public Schedule(Module module, byte day, byte hour, Timestamp createdAt, Timestamp updatedAt) {
		this.module = module;
		this.day = day;
		this.hour = hour;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	public byte getDay() {
		return this.day;
	}

	public void setDay(byte day) {
		this.day = day;
	}

	public byte getHour() {
		return this.hour;
	}

	public void setHour(byte hour) {
		this.hour = hour;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

}
